theme: jekyll-theme-minimal
title: R. Tyler McLaughlin, PhD
description: Seeking data scientist positions or industry roles at the interface between molecular systems biology and machine learning for biomedical innovation.
linkedin: https://www.linkedin.com/in/r-tyler-mclaughlin-phd
github_username: TylerMcLaughlin



markdown: kramdown
